docs: Add exercise questions for chapter 1 and some answers.
JSYoo5B/os_concept_10th pull request #1
Opened 2022-06-11 14:15 UTC by milsakim

Add answers for number 12, 13, and 14.

2022-06-11 14:32 UTC, JSYoo5B requested changes
아래 리뷰를 고려하여 마크다운 문법 지원에 맞게 수정하는 것을 권장드립니다.

2022-06-11 14:32 UTC, JSYoo5B commented on Chapter 1. Introduction/HyejeeKim.md
> +**g. Cache**
Github에서 렌더링 하는 마크다운 문법에서는 중간에 line break가 없으면 한번에 이어지게 됩니다.
[미리보기를 참고하시기 바랍니다.](https://github.com/JSYoo5B/os_concept_10th/blob/4528d986a4de1fe008c18bf133173cd4d94d4870/Chapter%201.%20Introduction/HyejeeKim.md)

짧은 line break는 이전 라인 뒤에 스페이스 2칸을 추가하면 됩니다.

2022-06-11 14:32 UTC, JSYoo5B commented on Chapter 1. Introduction/HyejeeKim.md
> +c. Distributed systems
위 리뷰와 동일

2022-06-11 14:32 UTC, JSYoo5B commented on Chapter 1. Introduction/HyejeeKim.md
> +c. A neighborhood
위 리뷰와 동일

2022-06-12 08:09 UTC, JSYoo5B approved these changes
PR 단위 기준으로는 문제가 없어 보입니다.

다만 커밋 단위로 봤을 때 제목의 수정 내역과 실제 수정되는 내용이 조금 섞여 잇는 것 같습니다.
연습을 위해 커밋을 적당히 분리해보는 연습을 해 보시는게 어떨까요?

2022-06-12 08:09 UTC, JSYoo5B commented on Chapter 1. Introduction/HyejeeKim.md
> +**c. The CPU is allowed to execute other programs while the DMA controller is transferring data. Does this process interfere with the execution of the user programs? If so, describe what forms of int
이 부분은 답안을 작성하는 것이 아니라 표현 방식을 수정하는 것으로 보입니다.

현재 commit 제목이 18, 19, 20, 21번에 대한 답을 하는 것이니, 커밋을 분리해서 작성해 보는 것이 어떨까요?

2022-06-12 08:09 UTC, JSYoo5B commented on Chapter 1. Introduction/HyejeeKim.md
> +**g. Cache**
첫 커밋 올라왔을때 수정 추천한 내역인데, 이 부분은 따로 커밋을 만들지 말고, 첫 커밋에서 해당 내용을 수정하여 적용해보세요.

2022-06-12 08:09 UTC, JSYoo5B commented on Chapter 1. Introduction/HyejeeKim.md
> +**g. Cache**
첫 리뷰에서 요청한 수정사항 같이 적용해보세요.

2022-06-12 08:12 UTC, milsakim commented on Chapter 1. Introduction/HyejeeKim.md
> +**c. The CPU is allowed to execute other programs while the DMA controller is transferring data. Does this process interfere with the execution of the user programs? If so, describe what forms of int
답변과 표현 방식 수정, 두 개의 커밋으로 분리해보는걸로 이해했는데 맞나요?

2022-06-12 08:14 UTC, JSYoo5B commented on Chapter 1. Introduction/HyejeeKim.md
> +**c. The CPU is allowed to execute other programs while the DMA controller is transferring data. Does this process interfere with the execution of the user programs? If so, describe what forms of int
네 맞습니다.
지금 이 커밋 외에도 오늘 추가된 2개 커밋에 지금 제목과 변경 내용이 혼재되어있는 것 같습니다.

2022-06-12 09:08 UTC, JSYoo5B commented
수고하셨습니다.

2022-06-12 09:09 UTC, merged