ch03 Programming Problem 21번, ch04 Practice 풀이
JSYoo5B/os_concept_10th pull request #15
Opened 2022-07-17 04:57 UTC by java-saeng

2022-07-17 05:14 UTC, JSYoo5B requested changes

2022-07-17 05:14 UTC, JSYoo5B commented on ch03/programming-problem/ps21.c
> +    child_pid = fork();
3.21 문제의 주요 핵심은 다음과 같습니다.

1. `fork()`로 자식 프로세스에서 콜라츠 수열을 만듬
2. 부모 프로세스는 자식이 완료될 때 까지 `wait()` 등으로 종료되지 않고 기다려야 합니다.
3. 수열을 만들기 전에 입력 값을 검증하는 (양의 정수가 들어오는지) 절차가 필요합니다.
4. 문제에서 command line이라 함은, 아마도 `scanf()`같은 입력 함수를 사용하는 것이 아닌,  
   명령어와 같이 전달하는 경우를 뜻하는 것으로 보입니다.  
   https://www.tutorialspoint.com/cprogramming/c_command_line_arguments.htm  
   위 링크와 `atoi()` 함수를 찾아보시기 바랍니다.

2022-07-17 05:14 UTC, JSYoo5B commented on ch04/practice/hyeonwoo.md
> +
암달의 법칙은 잠깐 찾아봐도 이해하는데 크게 어렵지 않으리라 생각됩니다. 아직 시간이 남았으니 조금 더 공부해 보시는건 어떨까요?

2022-07-17 08:23 UTC, java-saeng commented on ch03/programming-problem/ps21.c
> +    child_pid = fork();
아,, 아예 문제 해석을 잘못했군요 빠르게 수정해보겠습니다

2022-07-17 08:41 UTC, java-saeng commented on ch03/programming-problem/ps21.c
> +    child_pid = fork();
수정했습니다 !

2022-07-17 08:41 UTC, java-saeng commented on ch04/practice/hyeonwoo.md
> +
넵 알겠습니다 !

2022-07-17 08:52 UTC, JSYoo5B requested changes
[01db984](https://github.com/JSYoo5B/os_concept_10th/pull/15/commits/01db9844bd093510dc6658af633a23ab0419b8ce) 커밋은 [4e97a84](https://github.com/JSYoo5B/os_concept_10th/pull/15/commits/4e97a841b5fa293d151250dfc7df39009cf5e475)으로 sqaush해도 될 것 같습니다.

그리고 [a4a40b4](https://github.com/JSYoo5B/os_concept_10th/pull/15/commits/a4a40b481c3644e10b16cf7c842fd8b72c182a47)의 경우, `refactor` 헤더가 어울리지 않는 것 같습니다.

2022-07-17 09:06 UTC, java-saeng commented
> 그리고 [a4a40b4](https://github.com/JSYoo5B/os_concept_10th/pull/15/commits/a4a40b481c3644e10b16cf7c842fd8b72c182a47)의 경우, `refactor` 헤더가 어울리지 않는 것 같습니다.

헤더를 바꾸려고 해당 git reset --soft [커밋 ID]를 하고 git restore --staged . 를 하니 암달의 법칙 문제가 풀었던 커밋이 사라져버려가지구 git commit --amend를 하고 git push -f를 했는데 암달의 법칙 풀이가 같이 push 되어버렸네요,

2022-07-17 09:30 UTC, JSYoo5B commented
오늘 커밋 쪼개는 방법 연습하겠습니다.

2022-07-24 13:26 UTC, JSYoo5B approved these changes
오타 수정이나 커밋 쪼개는 연습하시고 알려주시면 머지해놓겠습니다.

말씀드렸듯 22번은 따로 PR 만들어서 보내는 걸 추천드립니다.

2022-07-31 06:05 UTC, java-saeng commented
커밋 쪼개기 연습했습니다 ! 맞는지 확인 부탁드립니다!!

2022-07-31 06:28 UTC, JSYoo5B approved these changes
네 맞습니다. 수고하셨습니다.
직접 머지하셔도 됩니다.

2022-07-31 06:29 UTC, merged