feat : Lottery Scheduling 추가
JSYoo5B/os_concept_10th pull request #33
Opened 2022-09-16 02:46 UTC by java-saeng

구글링과 다른 스터디원 분들이 작성하신 Lottery Scheduling 을 공부하고,
이해하면서 뇌피셜로 장점과 문제점을 한 번 작성해보았습니다

2022-09-16 03:37 UTC, JSYoo5B requested changes
전체적인 분석 내용에서 자료 조사가 부족했던 것으로 보입니다. 추가적인 자료조사 및 분석이 필요할 것 같습니다.

2022-09-16 03:37 UTC, JSYoo5B commented on Lottery-Scheduling/hyeonwoo.md
> +근데 OS 를 만든 사람이 어떠한 결과가 나올지 전혀 예상하지 못하고 해결할 수 없을텐데, 이러면 원하지 않는 결과가 나올 수 있지 않을까?
자료조사 및 분석이 다소 부족해 보입니다. 조금 더 자료를 찾아보시기 바랍니다.

2022-09-16 07:49 UTC, java-saeng commented on Lottery-Scheduling/hyeonwoo.md
> +근데 OS 를 만든 사람이 어떠한 결과가 나올지 전혀 예상하지 못하고 해결할 수 없을텐데, 이러면 원하지 않는 결과가 나올 수 있지 않을까?
넵 알겠습니다 !

2022-09-23 14:44 UTC, JSYoo5B approved these changes

2022-09-23 14:45 UTC, merged