[WiP] [docs] 공룡책 6장 practice & exercise 문제 풀이
JSYoo5B/os_concept_10th pull request #34
Opened 2022-09-18 03:34 UTC by JJSuBin

+ 공룡책 6장 practice 문제 풀이
+ 공룡책 6장 exercise 6.9, 6.10 문제 풀이

2022-09-18 15:12 UTC, JSYoo5B commented on ch06/practice/subin.md
> +4. 환형 대기 : 자원할당 그래프를 그려 할당과 요청의 상태를 보았을 때 환형(cycle)의 그림이 보이는 상태
이 부분은 오늘 미팅때 이야기했듯, 데드락 관련 대기 설명으로 보입니다. 다시 검토해보고 수정해주세요.

2022-09-18 15:13 UTC, JSYoo5B commented on ch06/practice/subin.md
> + 두 개의 세마포어 연산이 원자적으로 실행되지 않으면 두 연산이 모두 세마포어 값을 감소시키기 때문에 상호 배제를 위반한다.
맥락상 중요한 부분은 다뤘으나, 핵심이 되는 부분은 놓친 것 같습니다. 이전 미팅때 이야기했던 내용을 바탕으로 다시 수정해보세요.

2022-09-18 15:14 UTC, JSYoo5B requested changes
수고하셨습니다.
주요 답변 중 잘못되었던 부분 위주로 수정해서 검토 요청해주세요.

2022-09-18 15:15 UTC, JSYoo5B commented
>     * 공룡책 6장 exercise 6.9, 6.10 문제 풀이

현재 진도에서 exercise 부분은 다음주로 미루기로 했으니 이 부분도 수정해보세요.

commit에는 영향을 미치지 않지만, PR 단위로 기록하는데 있어서 기록을 잘 남겨놓는 연습을 해 보는 것이 좋을 것 같습니다.

2022-09-24 22:54 UTC, JJSuBin commented
위에서 말씀해주신 부분 모두 수정해봤습니다!

2022-09-24 22:56 UTC, JSYoo5B approved these changes
수고하셨습니다.

직접 머지하셔도 됩니다.

2022-09-24 22:58 UTC, merged