Chapter02 문제풀이
JSYoo5B/os_concept_10th pull request #5
Opened 2022-06-19 04:10 UTC by java-saeng

2022-06-19 04:47 UTC, JSYoo5B requested changes
현재 PR에 올라와 있는 커밋 중 대부분이 이미 작성되었던 내역과 중복되고 있습니다.

실질적으로 이번 과제로 반영할 만한 commit 목록은 cc999fd, 9e23825, f9480f1 세 가지로 보입니다.

rebase와 reset, cherry-pick 등을 활용하여 현재 pull request를 올린 브랜치에 위 3개 commit에 해당하는 내용만 있게 수정해 보시기 바랍니다.

(cherry-pick은 강의 중에 설명한 적은 없지만, 문서나 블로그를 찾아보면 쉽게 이해하실 수 있을 것이라 생각합니다.)

2022-06-19 06:48 UTC, java-saeng commented
> 현재 PR에 올라와 있는 커밋 중 대부분이 이미 작성되었던 내역과 중복되고 있습니다.

이와 같은 상황이 일어난 이유가 제가 upstream을 add하고 push할 때 force로 하지 않았기 때문일까요?

2022-06-19 08:00 UTC, JSYoo5B commented
이건 실습 시간에 보여드리면서 설명드릴게요

2022-06-20 08:19 UTC, JSYoo5B approved these changes
알려드린대로 수정하느라 수고하셨습니다.

2022-06-20 08:20 UTC, merged